modify .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,27 +1,98 @@
+# This is the complex Travis configuration, which is intended for use
+# on open source libraries which need compatibility across multiple GHC
+# versions, must work with cabal-install, and should be
+# cross-platform. For more information and other options, see:
+#
+# https://docs.haskellstack.org/en/stable/travis_ci/
+#
+# Copy these contents into the root directory of your Github project in a file
+# named .travis.yml
+
+# Use new container infrastructure to enable caching
 sudo: false
+
+# Do not choose a language; we provide our own build tools.
 language: generic
+
+# Caching so the next build will be fast too.
 cache:
   directories:
-  - "$HOME/.ghc"
-  - "$HOME/.cabal"
-  - "$HOME/.stack"
-  - "$TRAVIS_BUILD_DIR/.stack-work"
+  - $HOME/.ghc
+  - $HOME/.cabal
+  - $HOME/.stack
+  - $TRAVIS_BUILD_DIR/.stack-work
+
+# The different configurations we want to test. We have BUILD=cabal which uses
+# cabal-install, and BUILD=stack which uses Stack. More documentation on each
+# of those below.
+#
+# We set the compiler values here to tell Travis to use a different
+# cache file per set of arguments.
+#
+# If you need to have different apt packages for each combination in the
+# matrix, you can use a line such as:
+#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
 matrix:
   include:
+  # Rely on stack for building.
+
+  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
+  # variable, such as using --stack-yaml to point to a different file.
+  - env: BUILD=stack ARGS=""
+    compiler: ": #stack default"
+    addons: {apt: {packages: [libgmp-dev]}}
+
+  #- env: BUILD=stack ARGS="--resolver lts-2"
+  #  compiler: ": #stack 7.8.4"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  #- env: BUILD=stack ARGS="--resolver lts-3"
+  #  compiler: ": #stack 7.10.2"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  #- env: BUILD=stack ARGS="--resolver lts-6"
+  #  compiler: ": #stack 7.10.3"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  #- env: BUILD=stack ARGS="--resolver lts-7"
+  #  compiler: ": #stack 8.0.1"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  # Has pandoc-1.19.2.4
+  #- env: BUILD=stack ARGS="--resolver lts-9.21"
+  #  compiler: ": #stack 8.0.2"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  # Has pandoc-2.7.3
+  #- env: BUILD=stack ARGS="--resolver lts-14.21"
+  #  compiler: ": #stack 8.6.5"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  # Has pandoc-2.18
   - env: BUILD=stack ARGS="--resolver lts-18.28"
     compiler: ": #stack 8.6.5"
-    addons:
-      apt:
-        packages:
-        - libgmp-dev
+    addons: {apt: {packages: [libgmp-dev]}}
+
+  # Nightly builds are allowed to fail
+  #- env: BUILD=stack ARGS="--resolver nightly"
+  #  compiler: ": #stack nightly"
+  #  addons: {apt: {packages: [libgmp-dev]}}
+
+  allow_failures:
+  - env: BUILD=stack ARGS="--resolver nightly"
+
 before_install:
-- openssl aes-256-cbc -K $encrypted_898f4aa69170_key -iv $encrypted_898f4aa69170_iv
-  -in travis.key.enc -out ~/.ssh/id_rsa -d
+- openssl aes-256-cbc -K $encrypted_898f4aa69170_key -iv $encrypted_898f4aa69170_iv -in travis.key.enc -out ~/.ssh/id_rsa -d
 - chmod 600 ~/.ssh/id_rsa
 - echo -e "Host 45.32.135.28\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
+# Using compiler above sets CC to an invalid value, so unset it
 - unset CC
+
+# We want to always allow newer versions of packages when building on GHC HEAD
 - CABALARGS=""
 - if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
+
+# Download and unpack the stack executable
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
 - mkdir -p ~/.local/bin
 - |
@@ -36,9 +107,10 @@ before_install:
   mkdir -p $HOME/.cabal
   echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
   echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
+
+
 install:
-- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
-  '?')]"
+- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - |
   set -ex
@@ -70,6 +142,7 @@ install:
       ;;
   esac
   set +ex
+
 script:
 - |
   set -ex
@@ -109,5 +182,4 @@ addons:
 
 after_success:
   - scp -P822 -o stricthostkeychecking=no -r  /home/travis/build/ajeep8/pandoc-csv2table/.stack-work/install/x86_64-linux/*/*/bin/pandoc-csv2table travis@45.32.135.28:~/
-
 
